version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
      include: "scope"
    labels:
      - "internal"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
      include: "scope"
    labels:
      - "internal"
    open-pull-requests-limit: 1
    versioning-strategy: increase