version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '/'
    commit-message:
      prefix: 'chore(deps):'
      include: 'scope'
    labels:
      - 'internal'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '/'
    commit-message:
      prefix: 'chore(ci):'
      include: 'scope'
    labels:
      - 'internal'
