name: Question
description: Ask a question related to the project
title: '[question]: '
labels: ['question']
body:
  - type: textarea
    id: question
    attributes:
      label: Question?
      description: Feel free to ask any question regarding the project.
    validations:
      required: true
