name: Tags
on:
  push:
    branches:
      - tag/[0-9]+.[0-9]+.[0-9]+
jobs:
  Changelog:
    name: Changelog
    runs-on: ubuntu-18.04
    env:
      CHANGELOG_FILE: CHANGELOG.md
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Check tag status
        id: check_tag
        run: |
          if [[ ! -f ${CHANGELOG_FILE} ]] || ! egrep '#+\s+'"${GITHUB_REF##*/}"'\s+\([0-9]{2}/[0-9]{2}/[0-9]{4}\)' ${CHANGELOG_FILE}; then
            echo "::set-output name=status::true"
            echo "::set-output name=tag_name::${GITHUB_REF##*/}"
          fi
      - name: Create pre-release
        if: steps.check_tag.outputs.status
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.check_tag.outputs.tag_name}}
          release_name: v${{steps.check_tag.outputs.tag_name}}
          draft: false
          prerelease: false
      - name: Generate changelog
        if: steps.check_tag.outputs.status
        env:
          GREN_GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm install github-release-notes
          npx gren changelog --generate --override --tags=all
          git add ${CHANGELOG_FILE}
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m "tag/${{steps.check_tag.outputs.tag_name}}"
          git push
          git push origin :${{steps.check_tag.outputs.tag_name}}
      - name: Delete pre-release
        if: steps.check_tag.outputs.status
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          route: DELETE /repos/${{github.repository}}/releases/${{steps.create_pre_release.outputs.id}}
          owner: ${{github.actor}}
          repo: 'shadocs'
          release_id: ${{steps.create_pre_release.outputs.id}}